sequenceDiagram
    participant browser
    participant server

 browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa
        activate server
        Note right of server: The server create a new object note
        server-->>browser: 201 Created {"message":"note created"} 
        deactivate server

Note right of browser: The browser executes the callback function that renders the notes